# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketCurlyB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Tabman', '~> 2.11'
  pod 'ExpyTableView'
  # Pods for MarketCurlyB

end
